### ISSUE TITLE
Private Key exposed in anonify repo

### ISSUE THREAD

**Issue by Aju100** [LayerXcom/anonify#217]
## Summary
the private key has been exposed in the config folder. Here is the link of it.
https://github.com/LayerXcom/anonify/blob/master/config/Enclave_private.pem

## weakness
- Cleartext Storage of Sensitive Information

**Comment by osuketh** [comment]
Thank you. The pem key is just for testing, so it's okay to publish it. I just fixed to make the file name easier to understand. https://github.com/LayerXcom/anonify/pull/218

**Comment by Aju100** [comment]
@osuketh  thank u for your quick response on it.
