### ISSUE TITLE
use suitable so file in each integration test

### ISSUE THREAD

**Issue by cipepser** [LayerXcom/anonify#311]
現状の`tests/integration`の結合テストでは、`ENCLAVE_DIR=example/erc20/enclave`で生成されたsoファイルが前提となっている。  
`init_enclave` の引数に`ENCLAVE_FILE` のpathを渡し、結合テストごとに切り替えられるようにする。
（`create_enclave`と`get_enclave_file_path`も合わせて修正）

**Comment by osuketh** [comment]
fixed in #302
