### ISSUE TITLE
コントラクト・deployerソースコード, dockerfileは別レポジトリで管理

### ISSUE THREAD

**Issue by osuketh** [LayerXcom/anonify#544]
### 現状の課題
* コントラクトソースコードが重複管理 (--> versionあげるごとにコピペが必要）
* anonify本体のバージョン変化とdeployer imageの変化が合い混ざって、気づけない->古いimage使ってしまう
* deployer docker imageの手動ビルド必要

### 詳細
* deployerのanonify-eth-driverの依存は消す
* mainにマージしたらdeployer docker image build & push
* mainマージごとにimage version&repository version管理
* anonify等リポジトリでのabi/bin利用は、node imageのdockerfileで `anonify-contract` リポジトリをgit cloneし、solcでビルドし利用。

**Comment by cipepser** [comment]
分割するまではtagをlatestではなく、`eth-deployer:v0.5.9`のように指定するようにします

**Comment by osuketh** [comment]
fixed by https://github.com/LayerXcom/anonify/pull/556
