### ISSUE TITLE
[refactor] enclaveの設定値はビルドパラメータとして集約されていたい

### ISSUE THREAD

**Issue by laysakura** [LayerXcom/anonify#642]
一番良さそうだなって思うことを雑に書きます。

Enclaveの設定値は、[ここ](https://github.com/LayerXcom/anonify/pull/641#discussion_r648227596)の教え通り、ライブラリのバイナリにstaticに書き込まれているべきです。
こういうのは本来（今みたいに）ハードコードもすべきじゃないし、ましてやコード中で散逸すべきでもない。

ビルドパラメータであるのが一番ですね。
build.rs が build.toml (特に規格があるわけではないと思うけど) みたいなの読む形式になっているかのが一番キレイそうだなって思いました。
(Makefileでも良い)

_Originally posted by @laysakura in https://github.com/LayerXcom/anonify/pull/641#discussion_r649018359_

**Comment by osuketh** [comment]
古来のissue関連づけておきます 🙄 
https://github.com/LayerXcom/anonify/issues/206

**Comment by laysakura** [comment]
😂 
#206 と完全に重複ですね。特に新しい情報があるわけでもないし、こちらはcloseします。
